import { app, BrowserWindow } from 'electron'
import ElectronStore from 'electron-store'
import { update } from './reducers'

import colors from 'colors'


export class Store extends ElectronStore {
  constructor() {
    // Note: `super` lets us access and call functions on object's parent (MDN)
    // We pass in our config options for electron-store
    // Per: https://github.com/sindresorhus/electron-store#options
    super({
      name: "store",
      defaults: storeDefault
      // schema: StoreSchema
    })
  }

  async dispatch(action, window = undefined) {

    if (!app.isPackaged) logTheAction(action)

    // Get next state. 
    // `update` function also updates `global.patches`.
    const nextState = update(store.store, action, window)

    // Apply next state to Store
    this.set(nextState)

    // Send patches to render proces
    const windows = BrowserWindow.getAllWindows()
    if (windows.length) {
      windows.forEach((win) => win.webContents.send('statePatchesFromMain', global.patches))
    }
  }
}

function logTheAction(action) {
  console.log(
    // `Action:`.bgBrightGreen.black,
    `${action.type}`.bgBrightGreen.black.bold,
    // `(Store.js)`.green
  )
}

const storeDefault = {

  // ----------- APP ----------- //

  appStatus: 'open',

  darkMode: 'match-system',

  // See Theme.js for how themes are define
  theme: {
    id: 'gibsons',
    baseColorScheme: 'match-app', // 'dark', 'light', or 'match-app'
    colorOverrides: [],
    backgroundComponent: {},
    editorTheme: ''
  },

  chromium: {
    themeSource: 'system',
    isDarkMode: false,
    isHighContrast: false,
    isInverted: false,
    isReducedMotion: false,
  },

  wizard: {
    showOptionalLinkFields: false,
    showOptionalImageFields: false
  },

  sourceMode: false,

  focusedWindowId: 0,

  prefs: {
    isOpen: false
  },

  timing: {
    treeListFolder: 300,
  },

  markdown: {
    implicitFigures: true,
    emoji: true,
    strikethrough: true,
    taskLists: true,
    fencedCodeBlockHighlighting: false,
    allowAtxHeaderWithoutSpace: false,
    ulMarkerChar: '*'
  },

  // When tabbing through document, we can control which elements are tabbable
  tabbables: {
    blockquote: false,
    citation: true,
    code: false,
    emphasis: false,
    fencedcodeblock: false,
    footnote: true,
    // frontmatter: false // TODO
    header: false,
    hr: false,
    image: true,
    link: true,
    list: false,
    math: false,
    strikethrough: false,
    strong: false,
    taskList: false,
  },

  // Set of objects where key is doc id, and cursor position is 
  // recorded in `line` and `ch` properties.
  cursorPositionHistory: { },

  // ----------- PROJECTS ----------- //

  projects: {
    allIds: [],
    byId: {}
  }

  // projects: []

}

export const newPanel = {
  status: '', // E.g. 'userWantsToLoadDoc'
  index: 0,
  id: '', // Generate with nanoid
  docId: '',
  width: '100', // Percentage
  unsavedChanges: false
}

export const newProject = {

  // Used to associate windows with projects. Generated by nanoid.
  // id: '',
  
  window: {
    // Used to associate windows with projects
    id: 0,
    // Used when closing window (to check if it's safe to do so or not)
    status: 'new',
    isDraggedOver: false,
    bounds: { x: 0, y: 0, width: 1600, height: 1200 }
  },

  // User specified directory to folder containing their project files
  directory: '',

  // User specified path to CSL-JSON file containing their citatons
  citations: '',

  focusedSectionId: 'sidebar',
  
  // Index of focused panel
  focusedPanelIndex: 0,

  // draggedFileId: '',

  // A copy of the object of the document currently visible in the editor.
  // TODO: Is made obsolete by switch to panels. Remove.
  openDoc: {},

  // List of the open panels
  // See `newPanel` for template
  panels: [],

  // SideBar
  sidebar: {
    isOpen: true,
    isPreviewOpen: true,
    activeTabId: 'project',
    width: 250,
    tabsById: {
      project: {
        title: 'Project',
        lastSelected: {}, // id
        selected: [], // Array of ids
        expanded: [], // Array of folder ids
        sortBy: 'By Title',
        sortOrder: 'Ascending'
      },
      allDocs: {
        title: 'All Documents',
        lastSelected: {},
        selected: [],
        sortBy: 'By Title',
        sortOrder: 'Ascending'
      },
      mostRecent: {
        title: 'Most Recent',
        lastSelected: {},
        selected: [],
        sortBy: 'By Title',
        sortOrder: 'Ascending'
      },
      tags: {
        title: 'Tags',
        lastSelected: {},
        selected: [],
        sortBy: 'By Title',
        sortOrder: 'Ascending',
        selectedTags: []
      },
      media: {
        title: 'Media',
        lastSelected: {},
        selected: [],
        sortBy: 'By Name',
        sortOrder: 'Ascending'
      },
      citations: {
        title: 'Citations',
        lastSelected: {},
        selected: [],
      },
      search: {
        title: 'Search',
        lastSelected: {},
        selected: [],
        queryValue: '',
        inputToFocusOnOpen: 'search',
        options: {
          isOpen: false,
          matchCase: false,
          matchExactPhrase: false,
          lookIn: '*',
          tags: []
        },
        replace: {
          isOpen: false,
        }
      }
    },
    tabsAll: ['project', 'allDocs', 'mostRecent', 'tags', 'media', 'citations', 'search']
  }
}
